name: Frontend CI

on:
  pull_request:
    branches: 
      - fe/dev
    types: 
      - closed 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: next start
        uses: appleboy/ssh-action@master
        with: 
          host: ${{secrets.FE_HOST}}
          port: ${{secrets.FE_PORT}}
          username: ${{secrets.FE_USERNAME}}
          password: ${{secrets.FE_PASSWORD}}
          script: |
            ls -al
            cd /home/web17-waglewagle
            git pull origin fe/dev
            cd frontend
            npm i
            npm build
            pm2 kill -all
            pm2 start "npm start"
